spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imageprocessordb
    username: imageprocessor
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: imageprocessor
    password: password
    virtual-host: /
server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG