spring:
  application:
    name: image-processor

app:
  jwt:
    secret: yourverylongandsecuresecretkeyherewithlotsofentropy
    expiration: 36000000
  quota:
    daily-images: 50

file:
  upload-dir: /home/bruno/image-processor/uploads

rabbitmq:
  queue:
    image-processing: imageProcessingQueue
  exchange:
    name: imageExchange
  routing:
    key: image.processing.*

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings